export const plane = <i className="fa-solid fa-plane"></i>;
export const blog = <i className="fa-solid fa-blog"></i>;
export const edit = <i className="fa-solid fa-pen-to-square"></i>;
export const trash = <i className="fa-solid fa-trash"></i>;
export const plus = <i className="fa-solid fa-plus"></i>;
export const signout = <i className="fa-solid fa-right-from-bracket"></i>;
export const user = <i className="fa-solid fa-user"></i>;
export const facebook = <i className="fa-brands fa-square-facebook"></i>;
export const instagram = <i className="fa-brands fa-square-instagram"></i>;
export const twitter = <i className="fa-brands fa-square-x-twitter"></i>;
export const arrowRight = <i className="fa-solid fa-arrow-right"></i>;
export const arrowLeft = <i className="fa-solid fa-arrow-left"></i>;
export const people = <i className="fa-solid fa-universal-access"></i>;
export const star = <i className="fa-solid fa-star"></i>;
export const poll = <i className="fa-solid fa-square-poll-vertical"></i>;
export const location = <i className="fa-solid fa-location-dot"></i>;
export const idCard = <i className="fa-solid fa-id-card"></i>;
export const email = <i className="fa-solid fa-envelope"></i>;
export const phone = <i className="fa-solid fa-phone"></i>;
export const address = <i className="fa-solid fa-map-location-dot"></i>;
export const newspaper = <i className="fa-solid fa-newspaper"></i>
export const pencil = <i className="fa-solid fa-pencil"></i>;
export const menu = <i className="fa-solid fa-bars"></i>;
export const heart = <i className="fa-solid fa-heart"></i>
export const heartOutline = <i className="fa-regular fa-heart"></i>
export const hotel = <i className="fa-solid fa-hotel"></i>
export const room = <i className="fa-solid fa-door-open"></i>
export const image = <i className="fa-solid fa-image"></i>
export const wifi = <i className="fa-solid fa-wifi"></i>
export const gym = <i className="fa-solid fa-dumbbell"></i>
export const pool = <i className="fa-solid fa-water"></i>
export const trashcan = <i className="fa-solid fa-trash-can"></i>
export const support = <i className="fa-solid fa-headset"></i>
export const status = <i className="fa-solid fa-chess-board"></i>
export const gear = <i className="fa-solid fa-gear"></i>